### ISSUE TITLE
crash when selected "Accept HFS+ formatted Drives"

### ISSUE THREAD

**Issue by wukakuki** [SevenBits/Mac-Linux-USB-Loader#100]
I'm using OS 10.11.3 Beta (15D13b), mac linux usb loader 3.2(9345),kali 2.0.
It crash after I click the "create live usb" and choose the "kali-linux-amd64.iso" file , with "Accept HFS+ formatted drives" selected. Crash reporter below.
[“Mac Linux USB Loader” Sample.txt](https://github.com/SevenBits/Mac-Linux-USB-Loader/files/86338/Mac.Linux.USB.Loader.Sample.txt)

**Comment by SevenBits** [comment]
@wukakuki Hi there. Can I see this actual crash report as opposed to the process sample from Activity Monitor?

**Comment by wukakuki** [comment]
@SevenBits 
Oh! After updated to OS 10.11.4 Beta (15E27e), this problem fixed. I'm try to boot my mac from USB  drive now.But my usb drive didn't show up. And I had tried to set my usb drive as startup disk. It failed with "Failure to establish boot caches on boot assistant partition".How to fix it?

**Comment by SevenBits** [comment]
@wukakuki I’ve never seen this issue before. Can I see a screenshot of that error message and a copy of the system logs?

**Comment by wukakuki** [comment]
@SevenBits 
It crash again. Can't select HFS+ again.
That screenshot as .gif and the error log in uname.pdf
And my system logs as system.pdf(too much logs, I don't know which one you need)

[system.pdf](https://github.com/SevenBits/Mac-Linux-USB-Loader/files/90079/system.pdf)

![default](https://cloud.githubusercontent.com/assets/7627497/12319139/fee76ea6-bada-11e5-8911-ac64056d8348.gif)

[uname.pdf](https://github.com/SevenBits/Mac-Linux-USB-Loader/files/90068/uname.pdf)

**Comment by SevenBits** [comment]
@wukakuki Can you upload the screenshot as an actual video file? I can’t get enough details from that small gif...

**Comment by wukakuki** [comment]
@SevenBits Oh! I'm sorry! I didn't notice that. However, it can't open any more.
I can't send you mov files via github.
when I try to send you .mov file, this message shows up.
and the crash log.
[log.pdf](https://github.com/SevenBits/Mac-Linux-USB-Loader/files/92695/log.pdf)

"Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

**Comment by SevenBits** [comment]
@wukakuki Send me the log files over email.

**Comment by SevenBits** [comment]
Closing because there is no new information posted.
