### ISSUE TITLE
Not working for Xubuntu 15.10

### ISSUE THREAD

**Issue by danihodovic** [SevenBits/Mac-Linux-USB-Loader#103]
I've tried various combinations of options and the installation fails each time. First it complains that the kernel cant be found, but manages to boot to the Xfce loading screen. It then complains that it cant read from /dev/sdb which is the live-usb.

**Comment by SevenBits** [comment]
@danihodovic Please post your Enterprise configuration file (accessible from within the Setup USB Device window).

**Comment by SevenBits** [comment]
Closing since @danihodovic has not given any information to help fix the problem.

**Comment by danihodovic** [comment]
Yeah sorry about that. If I get around to installing Xubuntu again I'll try to provide the config. I installed Ubuntu gnome instead which worked fine.
