### ISSUE TITLE
After clicking on the live usb option and selecting the iso, nothing happens.

### ISSUE THREAD

**Issue by RikerW** [SevenBits/Mac-Linux-USB-Loader#107]
I click on the live usb option in the main menu thing.  The penguin with the `Create Live USB`.  

I selected the Linux Mint with cinnamon 64 bit iso.  I click open. 

Nothing happens.  The application is still open, but no new windows open.

I waited 15 minutes and still nothing happened.

I use OS X El Capitan (10.11) on a 2015 MacbookPro.

Clicking the icon in the dock just opens a new main menu, like at startup.

**Comment by SevenBits** [comment]
What version of OS X are you running?

**Comment by RikerW** [comment]
10.11

**Comment by RikerW** [comment]
And I think I found my problem, somehow a period got put after the filename, so it was `foo.iso.`, I think it rejected it as a invalid file.

**Comment by SevenBits** [comment]
That's probably it -- remove the period and see if it works.

**Comment by RikerW** [comment]
Did, thanks.
