### ISSUE TITLE
USB device not listed

### ISSUE THREAD

**Issue by charleswolfe** [SevenBits/Mac-Linux-USB-Loader#110]
2011 Mabook Pro running El Capitan 10.11.4 (15E65)

Tried sandisk 4gb, sandisk 16gb, and a 32 gb sandisk microsd
All formatted in diskutility as journaled hfs

**Comment by SevenBits** [comment]
@charleswolfe Could you describe how you fixed your problem/why you opened this issue, so that others who arrive here in the future can receive help if they had the same problem you did? Thank you.

**Comment by charleswolfe** [comment]
Must be formatted as FAT or FAT32

HFS is not going to work, or is supposed to, iirc.
