### ISSUE TITLE
Incorrect checking of value of "iso" entry in enterprise.cfg

### ISSUE THREAD

**Issue by karlic** [SevenBits/Mac-Linux-USB-Loader#111]
**Short Description of Problem:** Adding the line

    iso tails-i386-2.3.iso 

to enterprise.cfg causes Enterprise to check for existence of tails-i386-2.3.iso in / rather than /efi/boot/ on USB stick.

**Expected Behavior:** 

No output (warning message) when booting USB stick and selecting "1. Boot Linux from ISO file".

**Actual Behavior:** 

A warning message when booting USB stick and selecting "1. Boot Linux from ISO file".

    Warning: ISO file tails-i386-2.3.iso not found.

(Comes from lines 318--320 in main.c):

    if (!FileExists(root_dir, temp)) {
        Print(L"Warning: ISO file %a not found.\n", value);
    }

(I think root_dir is wrong.)

**Steps to Reproduce:** 

Follow steps in https://github.com/SevenBits/Mac-Linux-USB-Loader/wiki/Configure-booting-(one)-of-multiple-ISOs-(multiboot) and reboot USB stick

**Comment by SevenBits** [comment]
Thank you for finding the bug, but this should be filed under [SevenBits/Enterprise](https://github.com/SevenBits/Enterprise), as it is not related to Mac Linux USB Loader.

Also, :+1: for looking in the source code.
