### ISSUE TITLE
Kali Download Broken (I Have a Fix)

### ISSUE THREAD

**Issue by learntofly83** [SevenBits/Mac-Linux-USB-Loader#113]
Kali Wont Download from v 3.2.1 due to the source being http rather than https

A hack for the end user is:

(I'm using sudo as I've changed the default permissions to root:admin on the .app)

`sudo nano /Applications/Mac\ Linux\ USB\ Loader.app/Contents/Info.plist `

Change the last few lines from: 

```
        <string>https://www.sevenbits.tk/appcasts/mlul.xml</string>
</dict>
</plist>
```

TO:

```
        <string>https://www.sevenbits.tk/appcasts/mlul.xml</string>
        <key>NSAppTransportSecurity</key>
                <dict>
                        <key>NSAllowsArbitraryLoads</key>
                        <true/>
                </dict>
</dict>
</plist>
```

Then run (assuming you have Xcode installed)

`sudo codesign -fs - /Applications/Mac\ Linux\ USB\ Loader.app`

I'm assuming the author can programatically build this into the next version

LTF

**Comment by SevenBits** [comment]
@learntofly83 While this is a worthy hack, I'd like to avoid putting this into Mac Linux USB Loader. If, by the time of the next release, Kali _still_ has not enabled HTTPS for downloads, I will consider using a temporary exception to allow the app to use HTTP only with `kali.org`; other connections will still be forced to HTTPS.

**Comment by learntofly83** [comment]
Sure it was more of a letting you know of the issue with Kali and an interim workaround for end users ;)

Unbelievable Kali isn't delivered via https isn't it!

**Comment by SevenBits** [comment]
Yes, it's ironic that a distribution focused on security does not allow secure encrypted connections to their downloadable files.
