### ISSUE TITLE
custom kernel option (Number 9) doesn't seem to work.

### ISSUE THREAD

**Issue by dustingit** [SevenBits/Mac-Linux-USB-Loader#114]
**Short Description of Problem:** Under boot option 2 "Modify Linux kernel boot options" option "9" doesn't seem to work like other options.

**Expected Behavior:** 

If I choose option 9 it should change to yellow and then I should be able to hit "0" and hopefully specify an option like the initrd path so I can get different ISO's to work like ubuntu server

**Actual Behavior:** 
Doesn't change yellow and just hangs. Reboot required.

Boot to USB > Select option "2)" and then "9"

What I am trying to do is specify a custom initrd path so that I can try getting other ISO's to boot, like Ubuntu Server, or Pogostick. It would make this loader even more awesome. I have tried to specify the path in the .cfg file, which seemed to work, but get over written by some default configuration I am guessing.

Thanks for all your work thus far.

dustingit

**Comment by SevenBits** [comment]
Works for me. Maybe it is working on your system and the prompt just isn't showing up for whatever reason?

**Comment by dustingit** [comment]
Hey SevenBits,
Thanks for the response. I thought that maybe it working and just not
changing the text to yellow, but when I choose 9 and then 0 to boot, it
just hangs. I've tried it on two different Macs with the same results.

**Comment by SevenBits** [comment]
You don't press 9 and then 0 -- you press 9 and type the additional options that you want to pass to the kernel. When you press Enter, those options will be saved and the text will turn yellow. Then you press 0 to boot.

**Comment by dustingit** [comment]
Once I push the 9 it just sits there and doesn't respond to anything. I
will try the latest version and report back.

Thanks!

**Comment by SevenBits** [comment]
I've received several reports on this. Will do some testing and report back.

**Comment by SevenBits** [comment]
The issue should be resolved in the latest 3.3 beta; please try that. Closing for now.

**Comment by dustingit** [comment]
I am now  able to use option 9 and pass in kernel options. Thanks for working on it SevenBits!

**Comment by SevenBits** [comment]
@dustingit No problem!
