### ISSUE TITLE
Boot In OS X and Windows

### ISSUE THREAD

**Issue by ManuBermu** [SevenBits/Mac-Linux-USB-Loader#126]
Hello,

You can install Linux on a USB and you can start from both Windows and OS X? 
This can already be done by the installer Tails but not another Linux distribution.

**Comment by SevenBits** [comment]
@ManuBermu Please view the documentation:

https://github.com/SevenBits/Mac-Linux-USB-Loader/wiki/Frequently-Asked-Questions#1-does-mac-linux-usb-loader-support-uefi-based-pcs
