### ISSUE TITLE
Persistence Manager

### ISSUE THREAD

**Issue by clayauld** [SevenBits/Mac-Linux-USB-Loader#131]
**Short Description of Problem:** The persistence manager seems to work properly for a while then suddenly crashes the entire app. After that happens the persistence file seems to be the proper size.

**Expected Behavior:** 

I would assume the expected behavior should exhibit some sort of proper exit of the program where confirmation or errors are presented showing the results.

**Actual Behavior:** 

The app just crashes when nearing the end of the persistence setup.

**Steps to Reproduce:** 

This happens every time I try to do any persistence file setup.
[error log.pdf](https://github.com/SevenBits/Mac-Linux-USB-Loader/files/451573/error.log.pdf)

**Comment by SevenBits** [comment]
@clayauld Will close unless I hear more from you.

**Comment by clayauld** [comment]
Go ahead and close it.
