### ISSUE TITLE
Mac Linux USB Loader not working on my new Mac Book Pro

### ISSUE THREAD

**Issue by uxkenchris** [SevenBits/Mac-Linux-USB-Loader#133]
I downloaded the USB Loader program, it is not seeing my usb device.  USB Boot Controls and advanced configuration is greyed out.  My usb thumb drive is reformatted Master boot disc, should it be GUID?  it did not find that either.  How do i get it to show??

**Expected Behavior:**  

I should be able to select my usb drive

**Actual Behavior:** 

the installer cant find it, but disk utility and my desktop shows it

<img width="1280" alt="screen shot 2016-09-03 at 7 05 33 pm" src="https://cloud.githubusercontent.com/assets/5331590/18228640/fa5d6a28-720b-11e6-8675-20ea40433eaf.png">
<img width="1280" alt="screen shot 2016-09-03 at 7 04 08 pm" src="https://cloud.githubusercontent.com/assets/5331590/18228641/fa5e58c0-720b-11e6-8d70-c8d3de1a1b68.png">
<img width="1280" alt="screen shot 2016-09-03 at 7 17 04 pm" src="https://cloud.githubusercontent.com/assets/5331590/18228642/fa5e88cc-720b-11e6-996d-a590ff298e48.png">

**Steps to Reproduce:** 

put text here

*Note:* You can include screenshots and other media by dragging and dropping them onto this text area. Please do so, it helps solve your problem!

**Comment by SevenBits** [comment]
@uxkenchris Do you have the “enable hard drives” option enabled in the preferences?

**Comment by uxkenchris** [comment]
No I did not. Thanks!  From a UX standpoint. It may be handy to enable it for users and to have a step by step instructions on the site.

Best!!
A UX Designer.

**Comment by SevenBits** [comment]
@uxkenchris Did that solve your problem? If so, then please close out this issue.
