### ISSUE TITLE
Drop 10.8 support

### ISSUE THREAD

**Issue by SevenBits** [SevenBits/Mac-Linux-USB-Loader#136]
Should I drop support for OS X 10.8 Mountain Lion? I would love to be able to bump the minimum up to 10.9. This will give me the ability to eliminate lots of old code that I have to keep around the support 10.8.

Any thoughts? I will act unless people object.

**Comment by BanzaiTokyo** [comment]
Please don't. I am using a 17" MacBook Pro and 10.8 is the maximum supported version.

**Comment by SevenBits** [comment]
I have decided to retain support for 10.8 in version 3.4, to be released today. However, this will be the last release to support 10.8.
