### ISSUE TITLE
Where does the "Download This Distro" feature put the ISO image?

### ISSUE THREAD

**Issue by tbird20d** [SevenBits/Mac-Linux-USB-Loader#138]
**Short Description of Problem:** Can't find Ubuntu 16.04 image after downloading it.

**Expected Behavior:** 
I thought that the "Download This Distro" would put an iso image in my Mac Downloads directory.

**Actual Behavior:** 

After downloading Ubuntu 16.04 using the tool, I can't find the image.

**Steps to Reproduce:** 
Go to Distribution Downloader, Select Ubuntu 16.04, Click "Download This Distro".
Wait for distribution to download.

Look in Downloads folder - nothing there.  How do I find out where the iso downloaded to?
Nothing on the screen tells me the distribution was downloaded, or what to do next.

*Note:* You can include screenshots and other media by dragging and dropping them onto this text area. Please do so, it helps solve your problem!

**Comment by SevenBits** [comment]
@tbird20d It gets placed into a caches directory under the container directory in your user’s `Library` directory. If you want to install a distribution you’ve downloaded, just double-click on its name and the installer will open. If you want to find where it’s stored, right click on the name and select the option to view in the Finder.
