### ISSUE TITLE
Loader cannot be downloaded

### ISSUE THREAD

**Issue by GeorgesFM** [SevenBits/Mac-Linux-USB-Loader#139]
I just purchased this software and every time I try to install it, it gets an error message

![screen shot 2016-10-17 at 11 30 32 pm](https://cloud.githubusercontent.com/assets/22902578/19463417/dbcb4930-94c1-11e6-8719-d1716b456f7d.png)
I am unsure to why this is happening! Please help

**Comment by SevenBits** [comment]
@GeorgesFM What version of OS X are you running?

**Comment by SevenBits** [comment]
Closing due to lack of new activity.
