### ISSUE TITLE
Persistance manager slider size text display locks on user input

### ISSUE THREAD

**Issue by valtism** [SevenBits/Mac-Linux-USB-Loader#140]
**Short Description of Problem:** If the text box next to the size slider in Persistence Manager is selected and any key is pressed, the displayed value is locked at its current value and changing the slider no longer updates the text.

**Expected Behavior:** 

Displayed size should be as a label rather than a text box if uneditable, or the text box should take user input and change the slider upon input.

**Comment by SevenBits** [comment]
@valtism Thank you for your suggestion!
