### ISSUE TITLE
"The USB device that you have selected cannot be accessed because the system denied access to the resource."

### ISSUE THREAD

**Issue by hosam-ismail** [SevenBits/Mac-Linux-USB-Loader#143]
**Short Description of Problem:** 
Dear @SevenBits, i have read your faq https://github.com/SevenBits/Mac-Linux-USB-Loader/wiki/Frequently-Asked-Questions#4b-i-get-a-message-saying-the-usb-device-that-you-have-selected-cannot-be-accessed-because-the-system-denied-access-to-the-resource
and i can't find "Registered Devices".

I am using Mac linux usb loader version 3.1
Mac osx 10.11.6

how can i reuse the usb?

**Expected Behavior:** 

put text here

**Actual Behavior:** 

put text here

**Steps to Reproduce:** 

put text here

*Note:* You can include screenshots and other media by dragging and dropping them onto this text area. Please do so, it helps solve your problem!

**Comment by SevenBits** [comment]
It is on the main application menu, right where the About and Quit items are...
