### ISSUE TITLE
Won't find USB drive(s) on MacOS Sierra

### ISSUE THREAD

**Issue by forrie** [SevenBits/Mac-Linux-USB-Loader#144]
**Short Description of Problem:  I have two USB drives inserted into my Mac Pro cylinder that this program won't locate.

**Expected Behavior:** 

I should be able to select which USB to install the selected ISO on

**Actual Behavior:** 

There are no devices shown

**Steps to Reproduce:** 

I have two USBs mounted and verfied on the system; when I run this application and try to set up the ISO onto a device, there is nothing listed to select from.

*Note:* You can include screenshots and other media by dragging and dropping them onto this text area. Please do so, it helps solve your problem!

**Comment by SevenBits** [comment]
Have you checked whether or not the "enable hard drives" option is enabled?

**Comment by SevenBits** [comment]
Closing due to lack of new activity.

**Comment by TaciteOFF** [comment]
Same issue here on 10.12.4.

**Comment by SevenBits** [comment]
@TaciteOFF Do you have the ‘enable hard drives’ option on?
