### ISSUE TITLE
Persistence Issues Kali

### ISSUE THREAD

**Issue by dradosevich** [SevenBits/Mac-Linux-USB-Loader#145]
Issue:
The persistence manager doesn't seem to work for Kali distribution on my 2015 Macbook air. I use the persistence manager to create the persistence, but am unable to have files continue over between sessions. I have tried loading from the advanced boot option of persistence, as well as normally.
I have tried creating test text files, b ut they don't stay between sessions.

Expected behavior:
I would expect the files to stay between the sessions, which is need to continue using the appropriate drivers needed for macs.

**Comment by SevenBits** [comment]
@dradosevich Mac Linux USB Loader’s built-in persistence tool only works with Ubuntu. You must use an alternate procedure with Kali. [This video](https://www.youtube.com/watch?v=mDRbTHCoj8U) explains it very well, I believe.

(I don’t officially endorse the video.)
