### ISSUE TITLE
Actually practice the principles of open source

### ISSUE THREAD

**Issue by cbanowsky** [SevenBits/Mac-Linux-USB-Loader#146]
**Short Description of Problem:** 

This is lame

**Expected Behavior:** 

**FREE** and open source

**Actual Behavior:** 
$4.99 for Installer

**Steps to Reproduce:** 
go to your website

cloned, compiled, installed.  15 min - 20 min.

**Comment by SevenBits** [comment]
@cbanowsky I respect your opinion, but open source refers to free as in freedom, not free as in gratis. I have full-time responsibilities and cannot maintain this tool for free. Users are of course able to download and compile the source themselves as you have done if they believe that $4.99 is too much to ask.
