### ISSUE TITLE
Possible to boot Windows LiveCD?

### ISSUE THREAD

**Issue by GGGunrunner** [SevenBits/Mac-Linux-USB-Loader#147]
Thanks for this little utility - Kali boots just fine on my Macbook :)

This is not an issue, but rather a question: 

Is it possible to boot a Windows 8.1 based custom Rescue CD?
I have a distro of essential utilities (HDD cloners, Mem tests) and it would be fantastic to boot it from USB.

Thanks for your time!

**Comment by SevenBits** [comment]
Unfortunately, Windows is not supported, and probably never will be, since it is a proprietary OS with licensing restrictions tied to a particular computer. There are probably Linux equivalents for those tools, though.
