### ISSUE TITLE
Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.

### ISSUE THREAD

**Issue by invious** [SevenBits/Mac-Linux-USB-Loader#150]
Trying to do `pod install` have tried so many so-called fixes and have failed. I've been trying to do pod install for four hours now.

I've tried

1. `sudo xcode-select -r`

2.
```
rm -rf  ~/.cocoapods/repos/master
git clone https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master
```

and all manner of things.

**Comment by SevenBits** [comment]
@invious Honestly, you just need to install Cocoapods and run `pod install`. I’m not sure what you’re doing, because they have installation instructions on their site.

Closing because this is off-topic for this site.
