### ISSUE TITLE
Old kernel is loaded by default

### ISSUE THREAD

**Issue by schizoburger** [SevenBits/Mac-Linux-USB-Loader#159]
**Short Description of Problem:** 
I used Mac Linux USB Loader to create Live-USB with Kali Linux and set up the persistence storage. Unfortunately, on every startup old kernel is loaded, even though, the updated one is in the same folder (/lib/modules/).

**Expected Behavior:** 
Loader should use the newest kernel instead of the old one.

**Actual Behavior:** 
Loader installs the old kernel on every startup and uses it as default one. It's installed every time, because if I disable persistence I can only see the newest kernel in /lib/modules/, whereas if persistence is enabled, then there are the old one and the new one in the folder.

**Steps to Reproduce:** 
Installing the newest kernel:
apt-get update
apt-get install linux-headers-4.8.0-kali2-amd64
apt-get install linux-image-4.8.0-kali2-amd64

**Comment by SevenBits** [comment]
Mac Linux USB Loader loads kernel from inside of the distribution's ISO, not its persistence partition/file, so any kernels installed via persistence would not be detected.

Perhaps you can use Mac Linux USB Loader to create a Kali installer, and then install to an external SSD. Then you could customize the kernel from the install on the SSD.
