### ISSUE TITLE
Cannot find the ISO /efi/boot/boot.iso

### ISSUE THREAD

**Issue by M0ssMan** [SevenBits/Mac-Linux-USB-Loader#164]
I am on a Macbook Air (early 2015) running MacOS 10.11.6
Using a verbatim Store N Go V3 usb drive 15gb to try and load linux.
Trying to boot into linux ubuntu v16.04 desktop

I can boot into the EFI usb drive. And when it starts to load I get

![file_001](https://cloud.githubusercontent.com/assets/15313482/23589892/ed41d8e2-018a-11e7-9f19-a54b5c5a9bbe.jpeg)

It then continues to load ubuntu and I get the purple ubuntu loading screen.  Seconds later it kicks me back out to the command line.

I've tried multiple variations to see if I could boot.... often getting different errors on different variations of options I try.  The most common error is this one :

![file_000](https://cloud.githubusercontent.com/assets/15313482/23589905/37bcc45e-018b-11e7-906c-f537c4cdf445.jpeg)

obtained when booting with the following enterprise config settings (currently also trying with persistence but that hasn't changed anything):

entry Ubuntu
family Ubuntu
kernel /casper/vmlinuz.efi

I turned the logging on in the linux custom boot options and got some different logs(pics below) but ultimately the same thing happens almost every time. 

![file_002](https://cloud.githubusercontent.com/assets/15313482/23589941/c4966dc6-018b-11e7-858e-ea774b5ced47.jpeg)

![file_003](https://cloud.githubusercontent.com/assets/15313482/23589942/cc75f14c-018b-11e7-9f6d-00065715fceb.jpeg)

Any suggestions would be greatly appreciated.

**Comment by SevenBits** [comment]
@M0ssMan Ubuntu 16.04 is tested and confirmed to work. Sometimes bugs like this can happen for various reasons. Usually it is resolved by trying a different USB key.
