### ISSUE TITLE
How to make a persistent live USB with more than 4gb

### ISSUE THREAD

**Issue by julien-blanchon** [SevenBits/Mac-Linux-USB-Loader#168]
Hi, I have cd card with 128Gb and I want to install eOS with persistent partition. With Mac Linux USB Loader I can't make a persistent more than 4gb (and the persistent just not work with less :( ). I know it's a FAT32 limitation. But I don't find any working solution (something with partition but don't work). 

My SD is a 128GB [Lexar Pro 1000x](https://www.amazon.com/Lexar-Professional-UHS-II-Software-LSD128CRBNA1000/dp/B00PLENZPC).
And I use a macbook pro 13" 2015 (without gpu).

**Comment by chaunwleo** [comment]
@julien-blanchon may you specify your specs?

**Comment by SevenBits** [comment]
Unfortunately, you either need to use a partition or see if using another file system (such as HFS+, which Mac Linux USB Loader is experimental support for) will work.
