### ISSUE TITLE
parrot os

### ISSUE THREAD

**Issue by tortoledo70** [SevenBits/Mac-Linux-USB-Loader#169]
**Short Description of Problem:** Boot into my USB and says no img found. Ive had back box installed in my mac hard drive booting straight into back box as main boot. Ive been trying to use a new linux , I have deleted te partitions where ext4 and swap where located but no luck.
**Expected Behavior:** 
Now that backbox is deleted , I insert USB with new linux in it, the original back box live/ installation box appears and i try boot live then parrrot background comes out as if loading into it, then black grub screen appears that no file found.

**Actual Behavior:** 
This is my first post so please bear with me guys and gals.
 Tried once more but now debian boot screen  appears.

https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwin4P3_jKzTAhVGjFQKHWQkCZMQjRwIBw&url=http%3A%2F%2Faskubuntu.com%2Fquestions%2F121698%2Fhow-do-i-reset-a-lost-password-using-recovery-mode-requires-me-to-type-the-pass&bvm=bv.152479541,d.cGw&psig=AFQjCNGszZetfiui3YNAZrF76uMe0PPdsg&ust=1492539465833333
**Steps to Reproduce:** 

I created the new live USB using mac linux loader, normally before it would do enterprise.cfg for me but after installing in USB text edit screen appears

# enterprise.cfg
#
# This file is used to configure Enterprise. You need to fill out the following parameters according to how your desired Linux distribution configures its ISO file.

entry Custom Linux
kernel /path/to/kernel ...
initrd /path/to/initrd
# Please see https://sevenbits.github.io/Enterprise/ for more information.

If anyone may help it willbe appreciated, been going at this for 2 days with no luck. Once again bear with me , as this is my first post ever.

**Comment by SevenBits** [comment]
This page is for bug reports, not for help with unsupported distributions. If you are still trying to get this to work, please email me privately, or contact the developers of the distribution you want to load.
