### ISSUE TITLE
Mac Linux USB Loader not working new mac pro late 2016

### ISSUE THREAD

**Issue by gioferro96** [SevenBits/Mac-Linux-USB-Loader#174]
**Short Description of Problem:** The program works fine when creating a bootable USB for using Kali Linux live, but it's not working when I reload new macbook pro (13" late 2016). I choose the EFI boot (my USB key) and I just shows a black screen with a white cursor on it. I leave it for about 20 minutes and no changes appears.

**Expected Behavior:** 

Start Kali boot

**Actual Behavior:** 

Black screen with a white cursor

**Steps to Reproduce:** 

Create bootable USB, restart mac, choose EFI (not macintosh hd), press enter

**Comment by SevenBits** [comment]
Despite being a different Mac model, this issue seems very similar to the one described in #158. Please look in that thread, there is some good advice there.
