### ISSUE TITLE
I can't update this app

### ISSUE THREAD

**Issue by gusbemacbe** [SevenBits/Mac-Linux-USB-Loader#176]
**Short Description of Problem:** 

I checked for updates and I received the new update, but I didn't find any option of updating. I check for preferences and I tried to update anyway. I use 3.4.

**Comment by SevenBits** [comment]
Hi there,

The automatic updater only works when updating from 3.4.1. You will need to update manually.

**Comment by Timoofdoom** [comment]
Sorry to ask, but how do you update manually? do I go to the updates page and just download what's been updated since then?

**Comment by SevenBits** [comment]
You can download the update from the link you were given when you bought the app.

**Comment by Timoofdoom** [comment]
![screenshot 2017-06-22 17 30 35](https://user-images.githubusercontent.com/29613862/27458838-9f4cc6c4-5770-11e7-8c69-5e988580167d.png)

The link takes me to this page, and I've downloaded it 3 times.

**Comment by SevenBits** [comment]
And what version do you get when you click that link?

**Comment by Timoofdoom** [comment]
The one that I sent the other screen shot about? Says the year for it is
2012

**Comment by Timoofdoom** [comment]
I'm trying Etcher at the moment, so if that works, then it's no worries.

**Comment by gusbemacbe** [comment]
Timo, I contacted him. I downloaded from my email when I purchased and I
received download link. I updated to 3.4.2.

It could be 2012, but the link download always has been updated and you
just didn't reinstall and update. Download again from the download link you
received and reinstall and update.

Em 22/06/2017 19:46, "Timo" <notifications@github.com> escreveu:

**Comment by gusbemacbe** [comment]
Etcher fails for not including grub-efi-amd64.

Em 22/06/2017 19:50, "Gustavo Reis" <gusbemacbe@gmail.com> escreveu:

**Comment by Timoofdoom** [comment]
Oh, man. My bad. I had mixed up the previous downloads. Yeah, I got it now. Thanks for the help!
