### ISSUE TITLE
Mac Linus USB loader doesn't fully Load

### ISSUE THREAD

**Issue by Timoofdoom** [SevenBits/Mac-Linux-USB-Loader#177]
Not enough Preference options when opening up the program.

**Expected Behavior:** 

From what I understand, it should open up to several choices such as Create live usb, setup usb device, etc. 

**Actual Behavior:** 

It opens up a small window that lets you select a file from a dropdown and press a button that says "make live usb"

**Steps to Reproduce:** 

I've downloaded the link a couple times, and even tried parallel downloads I've found as well as trying to find the coding, but I'm not too good at that. Is there an auxiliary way to use it or have I downloaded the program wrong?
![screenshot 2017-06-21 15 57 12](https://user-images.githubusercontent.com/29613862/27406566-e1139802-569a-11e7-8d33-26e72a442c52.png)

*Note:* You can include screenshots and other media by dragging and dropping them onto this text area. Please do so, it helps solve your problem!

**Comment by SevenBits** [comment]
That is a very, very old version. You can get the latest version at the project website.
