### ISSUE TITLE
Can't find applesetos

### ISSUE THREAD

**Issue by dfb8085** [SevenBits/Mac-Linux-USB-Loader#178]
boots fine but gives error on finding applesetos 

**Expected Behavior:** 
no errors

**Actual Behavior:** 
error message

**Steps to Reproduce:** 

MacBook Pro 2016 13,2

*Note:* You can include screenshots and other media by dragging and dropping them onto this text area. Please do so, it helps solve your problem!

**Comment by Eno123456** [comment]
Same here

**Comment by SevenBits** [comment]
This is a bug that does not affect boot in any way. It will be gone in the next update.
