### ISSUE TITLE
Mac SSD not detected

### ISSUE THREAD

**Issue by dfb8085** [SevenBits/Mac-Linux-USB-Loader#179]
**Short Description of Problem:** put text here
When it comes time to do the partitioning step the SSD is not an option.
**Expected Behavior:** 
SSD be detected and able to construct partition

**Actual Behavior:** 
Only see the USB stick in the list

**Steps to Reproduce:** 

MacBook Pro 2016 13,2

*Note:* You can include screenshots and other media by dragging and dropping them onto this text area. Please do so, it helps solve your problem!

**Comment by SevenBits** [comment]
Have you checked to see that the “accept hard drives” option is enabled in the preferences?
