### ISSUE TITLE
Boot does not work

### ISSUE THREAD

**Issue by mateus007** [SevenBits/Mac-Linux-USB-Loader#181]
Using the software simple does not work. When I select to boot from USB, an black screen is shown, and nothing more...

I am using MacBook Pro 2016.

PS. Using dd command from ISO works beautiful, so its definitely is a problem with this App.

**Comment by SevenBits** [comment]
What distribution are you trying to boot? Have you viewed the FAQ pages?

**Comment by mateus007** [comment]
Ubuntu 17.04.
This could be related to issue #171

**Comment by SevenBits** [comment]
That very well could be. Have you tried any of the suggestions proposed in that thread? Have you tried booting with the 'nomodeset' kernel option available?

I'm not sure why Mac Linux USB Loader would fail when you claim DD works. The underlying code in Ubuntu is the same...

**Comment by SevenBits** [comment]
Closing due to lack of updates.
