### ISSUE TITLE
does not detected drives! just bought this software and can't use it ... 

### ISSUE THREAD

**Issue by jimmybaeyens** [SevenBits/Mac-Linux-USB-Loader#182]
Hi i want to create a drive and it does not see destinations... 

just bought this Dear jimmy,

Thank you for your purchase. Your Invoice ID is 6rz7fhqh6824ee92coz57afm888k08coowcwk4o.
<img width="737" alt="screen shot 2017-07-20 at 11 35 19" src="https://user-images.githubusercontent.com/16557147/28410963-8fcf0466-6d3f-11e7-8942-d3bc4a9cebc1.png">

**Comment by Eno123456** [comment]
Make sure the drive or partition you are using is set to the MS-DOS format.

**Comment by SevenBits** [comment]
@jimmybaeyens, have you followed the suggestion given by @Eno123456?
