### ISSUE TITLE
Launching Program Doesn't Bring Up Program Window

### ISSUE THREAD

**Issue by FromKansas** [SevenBits/Mac-Linux-USB-Loader#188]
Launch program and don't get this window.
![1](https://user-images.githubusercontent.com/30935894/29225842-6e70cf4a-7e95-11e7-8a5d-13cad5084e78.png)

What am I missing?

**Comment by SevenBits** [comment]
Did you click on its icon in the Dock?

**Comment by FromKansas** [comment]
Yes.  It brings Mac USB Linux Loader in the task bar.  All I can select is About Mac USB Linux Loader and Open.  I open my .iso file and get this. 
![untitled](https://user-images.githubusercontent.com/30935894/29226758-db19d5e4-7e98-11e7-8bd0-cfe45be43a07.jpg)

Drive won't show as available.

**Comment by FromKansas** [comment]
I am currently using macOS 10.12.5.

**Comment by SevenBits** [comment]
@FromKansas Is your USB FAT32 formatted? Have you followed all steps in the documentation?

**Comment by FromKansas** [comment]
Yes I have.  My main question is why do I not get the main option window when I first launch the program?

**Comment by SevenBits** [comment]
@FromKansas It should come up when you open the program, but if it doesn’t for some reason, you can show it by clicking the Dock icon or by doing View -> Welcome Screen in the menu bar.

**Comment by FromKansas** [comment]
Welcome Screen under View is not an option.  
![untitled2](https://user-images.githubusercontent.com/30935894/29228884-3f26fa00-7ea1-11e7-88ad-be568f1c6790.jpeg)

**Comment by SevenBits** [comment]
Look under Window then...

**Comment by FromKansas** [comment]
Not there either.  I have tried everything I can think.  Restarted the computer.  Uninstalled and reinstalled the software.  
![untitled3](https://user-images.githubusercontent.com/30935894/29229999-a8154eae-7ea6-11e7-9f0d-fc539cf1cd4a.jpeg)

**Comment by FromKansas** [comment]
![untitled4](https://user-images.githubusercontent.com/30935894/29230185-7c612bba-7ea7-11e7-9782-4110773ef93d.jpeg)

**Comment by SevenBits** [comment]
@FromKansas This is odd. Did you get the app from the official website?

**Comment by SevenBits** [comment]
Closing due to lack of updates.
