### ISSUE TITLE
Grant Access loop when trying to select iso

### ISSUE THREAD

**Issue by pvotava** [SevenBits/Mac-Linux-USB-Loader#191]
When selecting iso I am prompted to Grant Access, however selecting the button does not grant access.
<img width="570" alt="screen shot 2017-08-26 at 10 58 25 pm" src="https://user-images.githubusercontent.com/31380800/29747519-6188a8e2-8ab2-11e7-8e45-433fbddbbeb3.png">
 I have seen this issue listed before and tried your suggestions such as clearing registered devices and tried this line in terminal from prior string:
rm -R ~/Library/Containers/com.sevenbits.Mac-Linux-USB-Loader/
<img width="442" alt="screen shot 2017-08-26 at 11 03 10 pm" src="https://user-images.githubusercontent.com/31380800/29747535-e75c5716-8ab2-11e7-9736-006518272958.png">
Just purchased today, no issue with installation. Get to here:
<img width="714" alt="screen shot 2017-08-26 at 11 05 04 pm" src="https://user-images.githubusercontent.com/31380800/29747543-0cb93592-8ab3-11e7-96a8-f5db94c6bbe3.png">
But selecting Grant Access does nothing except refresh with the same screen. So when I cancel I get the following message.
<img width="628" alt="screen shot 2017-08-26 at 11 06 16 pm" src="https://user-images.githubusercontent.com/31380800/29747555-488fc9d2-8ab3-11e7-9173-ad1433e12c83.png">
I formatted the drive FAT 32, here is the info:
<img width="269" alt="screen shot 2017-08-26 at 11 18 01 pm" src="https://user-images.githubusercontent.com/31380800/29747613-1deae368-8ab5-11e7-8907-0c5e8599e154.png">

I hope I am not missing something simple, I am not a programmer so I was counting on the app to save some time and hassle, but disappointed after prepaying, the app seems straightforward and simple but I am stuck here, and apparently not an uncommon issue? 

*Note:* You can include screenshots and other media by dragging and dropping them onto this text area. Please do so, it helps solve your problem!

**Comment by SevenBits** [comment]
Hi @pvotava. The problem is with your third screenshot -- you need to select your USB drive (possible `L M`?) in the right panel. It should be selecting this for you, but I have heard that for some users, it doesn't for whatever reason.

**Comment by pvotava** [comment]
Ahhhhh yes and success. Thank you1
