### ISSUE TITLE
trackpad and keyboard not working on macbook 12 with linux mint

### ISSUE THREAD

**Issue by Afrika90** [SevenBits/Mac-Linux-USB-Loader#193]
**Short Description of Problem:** put text here
i've install a lix mint version with a dual boot on my macbook 12 early 2015, everything is working fine but the keyboard and trackpad doens't work, i've tried everything but nothing. If i use and external mouse and keyboard works fine. I've read something about but nothing to fix it. Any idea?

thanks 
**Expected Behavior:** 

put text here

**Actual Behavior:** 

put text here

**Steps to Reproduce:** 

put text here

*Note:* You can include screenshots and other media by dragging and dropping them onto this text area. Please do so, it helps solve your problem!

**Comment by SevenBits** [comment]
Similar issues have been reported before. Please try the solution suggested [here](https://github.com/SevenBits/Mac-Linux-USB-Loader/issues/158#issuecomment-288392912).
