### ISSUE TITLE
Botting from Usb linux mint 18.2 under iMac 21.5 mid 2010

### ISSUE THREAD

**Issue by yasslos** [SevenBits/Mac-Linux-USB-Loader#196]
Made a usb with Mac- linux loader get to booting and I get to
Loading Linux kernel... done

Loading initial RAM disc... done

Attempting to boot the Linux distribution now...
error: can't find command `applesetos'.
 After that the screen goes black, I can hear linux mint system Strat sound but that it s. Any help plz

**Comment by SevenBits** [comment]
There are many open threads that help with graphical values. You can also look in the FAQ section for help.
