### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by AleLoco** [SevenBits/Mac-Linux-USB-Loader#197]
<img width="155" alt="remote disk" src="https://user-images.githubusercontent.com/34719620/34220552-4ebce8b4-e5b5-11e7-80b1-d26f5ce08a4a.png">

Hello I need to uninstall the whole application, it seems putting it in the bin is not enough.
When I used my live USB, an unusual Remote Disk selection appeared in my device section and I cannot eject it… How can I delete this?

**Comment by SevenBits** [comment]
You can uninstall the application by removing it from your Applications folder.

Mac Linux USB Loader did not add the 'Remote Disk' option to your Finder. Perhaps you inserted a CD-ROM at some point.
