### ISSUE TITLE
sali

### ISSUE THREAD

**Issue by salimgb** [SevenBits/Mac-Linux-USB-Loader#199]
**Short Description of Problem:** put text here

**Expected Behavior:** 

put text here

**Actual Behavior:** 

put text here

**Steps to Reproduce:** 

put text here

*Note:* You can include screenshots and other media by dragging and dropping them onto this text area. Please do so, it helps solve your problem!

**Comment by SevenBits** [comment]
This is an empty issue with no details at all. Closing.
