### ISSUE TITLE
No options shown in "Choose Destination" window

### ISSUE THREAD

**Issue by sarky-de** [SevenBits/Mac-Linux-USB-Loader#202]
**Short Description of Problem:**
The window for selecting an USB drive is empty even though a drive is present and accessible via Finder. Selecting "Refresh" will still result in an empty window.
![screen shot 2018-04-29 at 6 30 38 pm](https://user-images.githubusercontent.com/10416100/39413164-78104bf2-4bdb-11e8-9515-4fc2b52b526e.png)

**Expected Behavior:** 
USB flash drive shows up in window and can be selected.

**Actual Behavior:** 
USB flash drive does NOT show up in window and therefore cannot be selected.

**Steps to Reproduce:** 
macOS Sierra 10.12.6

**Comment by SevenBits** [comment]
Have you verified that your USB drive meets the requirements as detailed in the program documentation?

**Comment by sarky-de** [comment]
Issue can be closed, thanks!

> Chances are that while the operating system says the USB drive is formatted as FAT, it might be formatted as another variant of FAT not supported by UEFI, such as exFAT. To resolve this issue, the drive should be reformated (WARNING: make sure there is no irreplacable data on the drive beforehand) to FAT32 (FAT) using Disk Utility.
