### ISSUE TITLE
Double-clicking in "Recent Distributions" only works once

### ISSUE THREAD

**Issue by fabjan** [SevenBits/Mac-Linux-USB-Loader#35]
The items in the list of Recent Distributions are double-clickable, and open the "Create Live USB" window on double-clicks. But it only works once per application boot. After the window has been opened once by double-clicking, double-clicking items in the "Recent Distributions" list does nothing.

## Steps to reproduce:

1. Start the application
2. Double click a distro in the "Recent Distributions" list
3. Close the creator window that opened
4. Double click a distro in the "Recent Distributions" list and see that no window opens

(Tried on a MacBook Air Mid 2011 with OS X 10.9)

**Comment by SevenBits** [comment]
Closing this; this issue is no longer relevant as of version 3.0.
