### ISSUE TITLE
Changes to finder on Yosemite

### ISSUE THREAD

**Issue by s34rch** [SevenBits/Mac-Linux-USB-Loader#54]
Running: 13 inch PowerMac 2.8 GHz Intel Core i7, 8GB RAM, 512GB HD, OS 10.10.1.

After installing Mac Linux USB Loader and using it, a change was made to the configuration of the OS.  Change includes altering Administrator privileges.  Now whenever I do anything in the Finder, such as copy files from one drive to another I must enter in my Administrator credentials.    This behavior did not happen prior to using Mac Linux USB Loader.  The addition of Mac Linux USB Loader was the only change I made to the software and applications of my Mac.

**Comment by SevenBits** [comment]
Closing since there has been no new posts here in almost two weeks.
