### ISSUE TITLE
Can't seem to get a working USB.

### ISSUE THREAD

**Issue by lkingjr** [SevenBits/Mac-Linux-USB-Loader#55]
I have tried to download Ubuntu, Linux Mint and Elementary from within the program. I created the USB but when I select EFI Boot it either freezes my iMac or it gets to the menu where I select 1. and then nothing.

I am running OSX 10.10.2 DP if that may be the issue.

**Comment by SevenBits** [comment]
I need more information from you, otherwise, this thread will be closed.

**Comment by lkingjr** [comment]
I can close it. I was just trying the loader but it doesn't seem to like 10.10.2 very much. Normally I just use hypervisors.
