### ISSUE TITLE
Experimenting with Kali

### ISSUE THREAD

**Issue by MrPutin** [SevenBits/Mac-Linux-USB-Loader#57]
Hello.

I'm on a Macbook Pro, mid 2010. Been trying out different install routes for Kali.
I've managed to get my Mac to boot the USB with both 1.- The default Enterprise with the current MLUSB-L 2.- The new Enterprise, by using the config file SevenBits recommended.

However every time I go on with the boot, I wait for a minute and I get an error saying "Unable to find a medium containing a live file system".
Any ideas?

I'll keep experimenting with different versions and architectures of Kali.

Cheers.

UPDATE.-1 Just tested booting kali-linux-1.0.7-i386. This time booting went further, showed configuring different devices and stuff until I got an error message saying "debian can't access tty job control turned off".

**Comment by jinxcy** [comment]
I wrote a guide to workaround this issue until SevenBits releases 3.1: 

https://docs.google.com/document/d/1nhdoftsGV0-7bpIw2K6lE7dgdTsOI_nV9YFSslHs02E/edit?usp=sharing

**Comment by SevenBits** [comment]
@jinxcy Cool, thanks for the contribution. I hope this proves helpful to someone.

**Comment by SevenBits** [comment]
@MrPutin @jinxcy A beta of Mac Linux USB Loader version 3.1 is out. Head over to the releases page to grab it.
