### ISSUE TITLE
USB drive not showing up

### ISSUE THREAD

**Issue by enzocagggiano** [SevenBits/Mac-Linux-USB-Loader#61]
When I try to create a live usb, my usb drive doesn't show up. I made sure its plugged in, tried reformatting it, erasing it with different filesystems, but nothing has worked. The usb drive shows up fine in finder and everywhere else (and in older versions of this app). I am using the latest version.

**Comment by kalihack2014** [comment]
@enzocagggiano  This is a known issue. The USB drive has to 4gb or less and formatting it to smaller partitions does not work either. Sevenbits told me about this.

**Comment by SevenBits** [comment]
This appears to be an OS X problem; I have tried looking into this in the past with no clear solution.

**Comment by enzocagggiano** [comment]
Ok, will it be fixed soon?

**Comment by enzocagggiano** [comment]
Ok, hope it is fixed soon. A 4GB usb drive works?

**Comment by kalihack2014** [comment]
@enzocagggiano  It worked for me but if you are trying to boot a Kali Linux distribution or Qubes I don't think anyone has been successful, except to boot Kali in Blind Mode which is completely useless...

**Comment by enzocagggiano** [comment]
I'm trying to boot ubuntu

**Comment by kalihack2014** [comment]
@enzocagggiano 
http://www.ubuntu.com/download/desktop/create-a-usb-stick-on-mac-osx

http://computers.tutsplus.com/tutorials/how-to-create-a-bootable-ubuntu-usb-drive-for-mac-in-os-x--cms-21253

These have worked for me perfectly!

**Comment by gorilla1977** [comment]
@enzocagggiano Actually, if you want to boot Ubuntu 14.10 you don't need MLUL (or any other EFI loaders)
Just "dd" the ISO image to your USB drive, and it should work right out of the box! ;-)

**Comment by enzocagggiano** [comment]
I get a no controller found error

**Comment by gorilla1977** [comment]
@enzocagggiano You need to add `nomodeset` to kernel booting options.
While booting, click `e` key to edit the entry for "Try Ubuntu without installing".
`By default, it contains:`
*set gfxpayload=keep*
*linux /casper/vmlinuz.efi  file=/cdrom/preseed/ubuntu.seed boot=casper quiet splash --*
*initrd /casper/initrd.lz*
`You need to change it into:`
*set gfxpayload=keep*
*linux /casper/vmlinuz.efi  file=/cdrom/preseed/ubuntu.seed boot=casper quiet splash* **nomodeset** *--*
*initrd /casper/initrd.lz*
After that it boots successfully.
**I already wrote about solution above in this thread - https://github.com/SevenBits/Mac-Linux-USB-Loader/issues/60 **

**Comment by enzocagggiano** [comment]
I got to the boot screen and the busybox window but now I get this error:
(Initramfs) Unable to find a medium containing a live file system

**Comment by gorilla1977** [comment]
@enzocagggiano That's very strange... Tell me please:
**1)** What is your hardware version of Mac? (that could be important)
**2)** What steps did you follow to create a bootable USB? What commands have you used?

**Comment by enzocagggiano** [comment]
1. MacBook Pro 17 Inch Late 2011
2. I used the enterprise files. I get to the normal ubuntu boot menu after vmlinuz kernel issues. I can't get the USB drive to boot with dd

**Comment by gorilla1977** [comment]
@enzocagggiano Could you show me the exact "dd" command that you have tried?
My hardware is similar to yours ( MBP 15" Early 2011 ) , but "dd" method worked for me at 1st try!

**Comment by enzocagggiano** [comment]
What did you format the USB drive to

**Comment by enzocagggiano** [comment]
sudo dd if=~/ubu.img of=/dev/rdisk1 bs=1m

**Comment by kalihack2014** [comment]
@enzocagggiano  did you convert the iso to a dmg? it looks like you are using an img

**Comment by enzocagggiano** [comment]
it has to be a dmg? it says to make a img on the official guide.

**Comment by kalihack2014** [comment]
@enzocagggiano  you have to convert the iso to a dmg via 
"hdiutil convert -format UDRW -o ~/path/to/target.img ~/path/to/ubuntu.iso"

then 
sudo dd if=/Users/johnnywinter/Downloads/ubuntu-14.04-desktop-amd64+mac.dmg of=/dev/rdisk2 bs=1m

Notice that the the ubuntu file is a .dmg 


In the official guide the not says "Note: OS X tends to put the .dmg ending on the output file automatically." 

and step 8 says:
Execute

sudo dd if=/path/to/downloaded.img of=/dev/rdiskN bs=1m
(replace /path/to/downloaded.img with the path where the image file is located; for example, ./ubuntu.img or ./ubuntu.dmg). <-------- here .dmg

**Comment by enzocagggiano** [comment]
ok

**Comment by kalihack2014** [comment]
@enzocagggiano  yes OSX uses dmg files not img lol should work now! :)

**Comment by enzocagggiano** [comment]
ok, I will tell you if i get an issue

**Comment by kalihack2014** [comment]
@enzocagggiano then do what gorilla1977 said when you get to GRUB2

"You need to add nomodeset to kernel booting options.
While booting, click e key to edit the entry for "Try Ubuntu without installing".
By default, it contains:
set gfxpayload=keep
linux /casper/vmlinuz.efi file=/cdrom/preseed/ubuntu.seed boot=casper quiet splash --
initrd /casper/initrd.lz
You need to change it into:
set gfxpayload=keep
linux /casper/vmlinuz.efi file=/cdrom/preseed/ubuntu.seed boot=casper quiet splash nomodeset --
initrd /casper/initrd.lz
/\/\/\
After these changes it boots successfully ;) If you want them by default, edit grub.cfg on USB drive.
I already wrote about the nomodeset solution above in this thread"

**Comment by enzocagggiano** [comment]
GOT IT TO WORK!

**Comment by kalihack2014** [comment]
@enzocagggiano  Knew you would ;)

**Comment by SevenBits** [comment]
@kalihack2014 @enzocagggiano FYI, guys, in the future, please avoid discussing software other than Mac Linux USB Loader. If you want to give each other support, please use an Internet forum or email each other privately.

**Comment by enzocagggiano** [comment]
ok

**Comment by kalihack2014** [comment]
@SevenBits Will do

**Comment by ParamaShiva1** [comment]
It is 2023 now and I am having this issue now. Can somebody please look into this. I have tried even a 2GB drive.
