### ISSUE TITLE
[Kali Linux] mount: mounting /dev/sda2 on /live/medium failed: Invalid argument

### ISSUE THREAD

**Issue by gorilla1977** [SevenBits/Mac-Linux-USB-Loader#64]
I decided to file this as a separate issue, because I haven't seen anyone telling about it.
During a process of booting Kali LiveUSB, just after *three pairs* of those messages:

    sd 6:0:0:0: [sdb] No Caching mode page found
    sd 6:0:0:0: [sdb] Assuming drive cache: write through

I see an error message which is being printed repeatedly for about a minute:

    mount: mounting /dev/sda2 on /live/medium failed: Invalid argument

Then I get the same report like everyone - `BOOT FAILED! This Debian Live image failed to boot.`

I've tried various kernel parameters, including those suggested at Enterprise website:
`kernel /live/vmlinuz boot=live noconfig=sudo username=root hostname=kali`

Also, I tried getting the latest version of MLUL from github repository and building it from source code (currently it is a few commits ahead of released 3.0.1 version)

However that didn't solve a "mount problem". Do you have any ideas?

**Comment by SevenBits** [comment]
Try the Debian mailing list. In the absence of a finished solution, they may be able to give you, the end users, some advice on this issue. Since Kali likely inherits its live USB setup procedure from Debian, this is worth considering.

Either that, or find an official email for someone at Offensive Security. Oddly, I can't seem to find one.

**Comment by gorilla1977** [comment]
@SevenBits I wrote to `debian-live` mailing list, and would contact Kali through forum or bug report.
But, sadly, I am not sure if anyone would help with this very specific issue... Debian guys could tell "that's not our problem, contact Kali" and Kali will tell that USB booting at MBPs that are older than "late 2012" (that includes all non-retina MBPs) is not supported by them, as they state in their manuals & forum threads. Unless someone knowledgeable arrives to this thread, guess I'm out of luck :disappointed:

**Comment by gorilla1977** [comment]
Small update: Debian Live developers refused to help and told me to contact Kali

**Comment by SevenBits** [comment]
@kalihack2014 @Addisonbean @Soap109 If anyone is waiting for a progress report on Kali, you'll be happy to see these photos.

![img_5474](https://cloud.githubusercontent.com/assets/2482736/6982863/56045cf8-d9e5-11e4-9d57-5ca8817cee9a.JPG)
![img_5475](https://cloud.githubusercontent.com/assets/2482736/6982866/5a05f942-d9e5-11e4-99b9-c7905aad7f99.JPG)

You'll have to wait for Mac Linux USB Loader 3.1, though...

**Comment by reaganrockz** [comment]
When do you think Mac Linux USB Loader 3.1 will be released?

**Comment by SevenBits** [comment]
@reaganrockz Sometime in the next week or two is the target.

**Comment by reaganrockz** [comment]
@SevenBits Ok thanks!

**Comment by SevenBits** [comment]
@reaganrockz A beta of version 3.1 is out... You can grab it on the releases page.

**Comment by reaganrockz** [comment]
Ok thank you @SevenBits!

**Comment by SevenBits** [comment]
Closing as version 3.1 has been released.
