### ISSUE TITLE
Issue with Kali Linux

### ISSUE THREAD

**Issue by lucvorringa** [SevenBits/Mac-Linux-USB-Loader#65]
I have an old laggy macbook 2010, and because of the laggs i decided to install Kali on my macbok.
At my first try, i completly formatted my hard drive.
After that, i installed on my other mac kali linux (live) on a usb stick with "Mac Linux USB Loader".
Now to my issue, when i start my mac from the usb stick, i get this error:,, modprobe: module swap not found in modules.dep", what can i do?

Sorry for bad englisch, i come from germany

**Comment by SevenBits** [comment]
This should be filed under SevenBits/Enterprise. Closing.
