### ISSUE TITLE
Linux Mint 17 : "unable to find a medium containing a live file system"

### ISSUE THREAD

**Issue by KeatsPeeks** [SevenBits/Mac-Linux-USB-Loader#66]
Hello.

I've been trying to install Linux Mint 17.1 x64 on my MBP mid-2014 running Yosemite, to no avail.
I followed the guide and tried several times with different options (all 4 combinations of the Ubuntu chekboxes), but it kept failing.

Just after the two initial menus, these errors appear : 
```
Loading Linux kernel...error: file /casper/vmlinuz.efi not found
Loading initial RAM disc...error: you need to load the kernel first
````

Then, a GRUB menu appears. I select the option to launch the OS and I can see the Linux Mint logo for a few seconds. 

Then, I get this fatal error : 
```initramfs : unable to find a medium containing a live file system```

Any ideas ? I don't have any casper folder on the usb stick, is that normal ?
Thanks.

**Comment by SevenBits** [comment]
@KeatsPeeks Hmm, the Linux Mint team must have changed something recently. I'll get on figuring out what's wrong.

For Linux Mint, you need to check **both** checkboxes on the setup screen. Did you do this?

**Comment by KeatsPeeks** [comment]
@SevenBits Sorry, I guess I lied when I said I tried all combinations, I must have forgot this one. It works well when both checkboxes checked.
Sorry to have opened an issue on this for nothing. Keep up the good work.

**Comment by cmivxx** [comment]
I am having the exact same problem on OSX Yosemite trying to load Mint 17.1.  The error persists whether I check both boxes or not on both the 3.0 version or the 3.1 BETA.  Any other ideas?  Any chance this would be alleviated by using Mint 17.0 or earlier?

**Comment by SevenBits** [comment]
@cmivxx Can you include a screenshot of the error message?

**Comment by cmivxx** [comment]
yeah, here you go.

http://imgur.com/a/1m9zy

**Comment by SevenBits** [comment]
@cmivxx And the error occurs with Enterprise 0.3 (the one included with the most recent beta)?

Please try with Linux Mint 17... perhaps that will fix the problem...

**Comment by cmivxx** [comment]
Will do..  I'll let you know how it goes.  Thanks for the help!

**Comment by WAFFO** [comment]
So cmivxx didn't come back, but I can verify that using Linux Mint 17 instead of 17.1 works. I believe I checked both boxes as well.
