### ISSUE TITLE
Project website page not found

### ISSUE THREAD

**Issue by hackerb9** [SevenBits/Mac-Linux-USB-Loader#70]
From the Welcome Screen, click on "More Options" and then "View Project Website", you will be taken to http://sevenbits.github.io/projects/mlul.html, which then shows a 404, not found error. 

Using version 3.0.2 (8093) on OS X 10.9.5.

[Completely tangential, but important: your work on this program is awesome. Thank you for creating this much needed tool and releasing it under the GPL.]

**Comment by SevenBits** [comment]
@hackerb9 This is corrected in version 3.1, which is currently in beta. It should be released soon, once any remaining bugs are fixed.

And thank you, I'm happy to help.
