### ISSUE TITLE
translation link is not found in homepage

### ISSUE THREAD

**Issue by Akagi201** [SevenBits/Mac-Linux-USB-Loader#74]
https://raw.githubusercontent.com/SevenBits/Mac-Linux-USB-Loader/stable/TRANSLATIONS
I digg the source code, this link is dead.

I'm glad to give a Chinese translation of the software and document. You can try <https://crowdin.com>. It's total free for open source projects. <https://crowdin.com/page/open-source-project-setup-request>

I am the Chinese translator of obs-studio software <https://crowdin.com/project/obs-studio>. The website is very friendly, easy to use.

**Comment by SevenBits** [comment]
Thanks @Akagi201, and yeah, I've been planning on creating a new file soon; I'm aware that the link is dead. I'm designing a new webpage for Mac Linux USB Loader so that should be there around the same time.

I'd be happy to have you translate. I will look into that website.

**Comment by SevenBits** [comment]
Closing as the website has been updated.
