### ISSUE TITLE
[FR] MacBook Air Mid 2014 - Tail Live USB

### ISSUE THREAD

**Issue by ghost** [SevenBits/Mac-Linux-USB-Loader#77]
ok so french keyboard.
strange bug, didn't work with a (more or less, not the exact sentence) strange error message as follow:
```invalid path: /live/wmlinu```
so in `USB Setup > Edit Entreprise Configuration File` 
i change this : `kernel /live/vmlinuz`
to this : `kernel /live/vmlinuzz`
and it worked !

**Comment by SevenBits** [comment]
This bug looks like it should filed under SevenBits/Enterprise.

What version of Enterprise and Mac Linux USB Loader are you using?

**Comment by jcanonym** [comment]
Mac Linux USB v.3.1 rev 9048.
For the Entreprise the one bundle with ML USB.

**Comment by SevenBits** [comment]
Hmm, this is weird, but this issue has been reported before. I'll look into it.

**Comment by SevenBits** [comment]
This issue has been fixed as of version 3.1, so I am closing this issue.
