### ISSUE TITLE
Problem with latest Kali version

### ISSUE THREAD

**Issue by agsola** [SevenBits/Mac-Linux-USB-Loader#78]
I have tried using Mac Linux USB Loader with the latest .iso from Kali (kali-linux-1.1.0a-amd64) but I couldn't make it work.

I attach two images with the error I get when booting.

Any idea?

First, it detects it:
![error-01](https://cloud.githubusercontent.com/assets/472079/8260007/3d5ef230-16c1-11e5-9acd-7d6617fa5a3e.JPG)

But then, it throws an error:
![error-02](https://cloud.githubusercontent.com/assets/472079/8260006/3d5442f4-16c1-11e5-8911-4ece5e62eedb.JPG)
It doesn't find the kernel, which I think is wrong (missing a "z"??).

**Comment by SevenBits** [comment]
What model MacBook do you have?

**Comment by agsola** [comment]
MacBook Air (13-inch, Mid 2013)

**Comment by SevenBits** [comment]
Please [contact me](https://sevenbits.github.io/contact.html), as I want to send you an updated build with some changes so that I can see if they fix these issues for you.

**Comment by powlwoq** [comment]
Hi 7bits,
i have the same issue with a MacBook Air (11-inch, 2015 [bought last month]).
Error msgs are the same like above with newest USB-Loader.
I can't even boot from external DVD - strange...
No chance to boot with newset rEFInd bootloader either (USB or DVD, 32 or 64bit).
I am really frustrated about this...
And I am thankful for any help out there.
Thanks in Advance,
powl

**Comment by SevenBits** [comment]
@powlwoq Please contact me, as I want to send you an updated build with some changes so that I can see if they fix these issues for you.

**Comment by SevenBits** [comment]
To anyone else having this issue, as a temporary workaround add an extra character to the end of the kernel file name in Enterprise configuration file (either .MLUL-Live-USB or enterprise.cfg, depending on which version of Mac Linux USB Loader you used).

**Comment by SevenBits** [comment]
This was fixed in the latest release so I am closing this issue.
