### ISSUE TITLE
Cannot find the ISO /efi/boot/boot.iso

### ISSUE THREAD

**Issue by skylar73** [SevenBits/Mac-Linux-USB-Loader#79]
I have recently tried to use Mac Linux USB Loader to put Ubuntu 15.04 (64 bit) onto my flash drive. When booting, it will show the ubuntu screen (with it loading), but then it will go to this error message:
![img_6383](https://cloud.githubusercontent.com/assets/12574140/8320619/4851b33a-19eb-11e5-93f7-68613b95de6d.JPG)

This same issue was brought up here: https://github.com/SevenBits/Mac-Linux-USB-Loader/issues/12 , but was never fixed. 

Additional details (that may have no relevance):
-Installed with persistence (max amount of GB, around 4.7 I think?)
-Booted and installed on a Mac with OS X Version 10.9.5
-Mac is a desktop from 2007

Thanks for your help!

**Comment by SevenBits** [comment]
Which version of Mac Linux USB Loader are you using?

FYI, this should be filed under SevenBits/Enterprise.

**Comment by skylar73** [comment]
3.0.2

**Comment by SevenBits** [comment]
Can you try the 3.1 beta and see if that fixes it?

**Comment by skylar73** [comment]
I did not try the 3.1 beta, but when I tried again on a different computer (Newer MacBook Pro, maybe mid 2013?), it worked. 

Thanks so much for your help and great program!!
