### ISSUE TITLE
Unknown error sending read/write command, card status 0x900

### ISSUE THREAD

**Issue by markwylde** [SevenBits/Mac-Linux-USB-Loader#85]
Hey, just tried your Mac Linux USB Loader and it's the closest I've got yet to having a LiveCD work, but unfortunately not there just yet.

I have tried both Debian and Ubuntu and the disk appears in the alt boot screen as expected. I select the disk and then it asks me what I would like to do. I hit 1, and then select Ubuntu (or Debian originally).

The screen flashes and then the text goes really small. This all seems fine, then after about 10 seconds I get the following:

![Screenshot of my Mac](http://i.imgur.com/LJByVb3.jpg)

I am using a MacBook Pro (Retina, 15-inch, Early 2013) 2.7GHz, i7 and the OSX on there is all up to date, running Yosemite 10.10.5

I am using a 128GB SD card from Transcend (JetDrive Lite 130) so it's not really a USB drive, but I presume that should be okay, since it gets to the boot screen and all okay.

Anyway fingers crossed someone has come across this and has an answer.

Sorry I should add I installed the following individually:

- ubuntu-14.04.3-desktop-amd64
- debian-live-8.2.0-amd64-kde-desktop

**Comment by SevenBits** [comment]
@markwylde Your SD card should work, but just to try ruling things out, could you try it on a standard USB drive? Based on the error messages it seems that Linux is having some difficulty reading the drive...

**Comment by markwylde** [comment]
Yeah it works as expected on a USB device :(

**Comment by SevenBits** [comment]
@markwylde Looks like Linux can't read from your SD card then. Maybe it's a driver issue. Regardless, it's an issue with Linux and not Mac Linux USB Loader.

**Comment by JasonJWilliamsNY** [comment]
I get a similar message. I have tried this with several different USB drives (8-16GB). It takes >1000 seconds to boot. Happy to provide more details - this is the first (nearly) working solution I've found. Thanks!
![img_8261](https://cloud.githubusercontent.com/assets/7266775/11156982/f29d189c-8a1c-11e5-946f-9bc6390a438c.JPG)

**Comment by SevenBits** [comment]
@JasonJWilliamsNY Does it ever boot completely? If it takes that long, my guess is that it's an I/O problem.
