### ISSUE TITLE
Mac-Linux-USB-Loader - in German?

### ISSUE THREAD

**Issue by wisdomlight** [SevenBits/Mac-Linux-USB-Loader#88]
Hi,
I've downloaded and opened the app.

I've downloaded it three times.

it's in German

Is there an English version?

Cheers

**Comment by SevenBits** [comment]
Mac Linux USB Loader appears in whatever language your system is set to. Change your system language to English if you want the app to be in English.

**Comment by tveloq** [comment]
I had the same issue although my system language was set to English.

In order to fix it I had to browse the app with "Show package contents" and delete the following folders:

/Contents/Resources/de.lproj
/Contents/Resources/es.lproj
/Contents/Resources/nl.lproj

**Comment by SevenBits** [comment]
@tveloq That's very strange. I'm not sure what could be causing it.

**Comment by borgesrodrigo** [comment]
i'm having the same issue.

**Comment by eMerzh** [comment]
Same here.. last version. the app is in NL and the system is in French...
i think the issue must be re-opened

**Comment by SevenBits** [comment]
@eMerzh Unfortunately, without a way to reproduce the problem on my end, it’s going to be very difficult to fix the problem, but fell free to re-open if the issue still exists.

**Comment by eMerzh** [comment]
@SevenBits OK... But thé issue is still there in thé last version. Juste donwloaded it, unzip then run. And i've not the ability to re open the issue.

It might be the code that determine the user's language or smth? Is there some way we can give you more info to put you on track?
