### ISSUE TITLE
Can't set persistence!

### ISSUE THREAD

**Issue by hpnishi** [SevenBits/Mac-Linux-USB-Loader#89]
I finally figured out how to create the live USB boot for Kali, but now I can't set persistence.
Mac Linux USB Loader doesn't show any pendrive:
![screen shot 2015-10-09 at 1 44 41 pm](https://cloud.githubusercontent.com/assets/15038783/10400006/a925ec30-6e8c-11e5-82f2-ab37867ac4b0.png)

Best regards,

**Comment by SevenBits** [comment]
In order for persistence to work with Kali, it must meet special requirements for security reasons. I believe you need to partition your USB drive. If you search on Google you can get more detailed information.

**Comment by bnhorowitz** [comment]
I just installed Ubuntu 18.04 on a USB and have the same problem as above. Mac Linux USB Loader does not recognize the USB drive to set persistence.
