### ISSUE TITLE
Slider does not show space for Persistance

### ISSUE THREAD

**Issue by AcexSpade** [SevenBits/Mac-Linux-USB-Loader#90]
Slider does not show space for Persistance on El Capitan with version 3.1

**Comment by SevenBits** [comment]
Can you be more specific? Perhaps include a screen shot?

**Comment by rohannarang15** [comment]
Setting the slider doesn't seem to update the value in the text box. It stays at 128 mb
![screen shot 2015-10-29 at 10 20 22 pm](https://cloud.githubusercontent.com/assets/15383644/10825916/25b79f2c-7e8d-11e5-8a8e-6e70b8b7dc05.png)
I went ahead and put the slider to its max value and pressed "Create Persistence" anyway. After the operation was done, I checked the size of the casper-rw file and it looks like the operation was successful.
![screen shot 2015-10-29 at 10 29 54 pm](https://cloud.githubusercontent.com/assets/15383644/10826014/ad6b3bcc-7e8d-11e5-9fc0-0bb9de6ac0d0.png)
So I think this is just a minor GUI bug. I'm using El Capitan.

**Comment by nnevvinn** [comment]
I had the same experience as rohannarang15 on 10.11.1 -- no response to moving slider, but created an ≈4gb file.

**Comment by SevenBits** [comment]
@nnevvinn @rohannarang15 This is a known issue. I will put out a fix ASAP.

**Comment by keyvanfatehi** [comment]
I have the same issue. Running OS X Yosemite

**Comment by SevenBits** [comment]
This issue has been fixed and the fix will be released within the next few days.
