### ISSUE TITLE
Cannot start Ubuntu from sub with mac Linux usb loader

### ISSUE THREAD

**Issue by Sedkol** [SevenBits/Mac-Linux-USB-Loader#92]
![image](https://cloud.githubusercontent.com/assets/13577322/11182162/edde24b0-8c68-11e5-87a0-187a8c742982.jpeg)
Hallo. Any known issues?

**Comment by SevenBits** [comment]
Closing because the OP did not give me any information on his system, as required by [the contribution guidelines](https://github.com/SevenBits/Mac-Linux-USB-Loader/blob/master/CONTRIBUTING.md).
