### ISSUE TITLE
Installation Options needs explanation

### ISSUE THREAD

**Issue by SeanFelipe** [SevenBits/Mac-Linux-USB-Loader#97]
At the final screen, a couple options appear which, to me at least, are a bit obscure. 'This ISO lacks an EFI-enabled kernel' and 'This ISO has code older that Ubuntu 14.10'.

Not being intimately familiar with these aspects of Linux -- the Ubuntu versioning system is straightforward I suppose, but pretty annoying to me -- I really have no idea what to select. I'm installing the latest version of Mint, which is based on a new Ubuntu, so I guessed that I don't have code older than 14.10. But 'has code that is older' -- I'm sure some of the thousands of packages in Mint are older than 2014. I assume this refers to core functionality or kernel level code? But there's no details or context, so that's pretty confusing.

Can we have some explanation of what these options mean, how to find out the answer, and why it's important? Without explanation, it just creates uncertainty for those who are not up to speed with the technology.

Thanks for the tool - I donated!

**Comment by SevenBits** [comment]
@SeanFelipe I'll do a full write-up tomorrow. Thanks for sharing your feedback!

**Comment by SevenBits** [comment]
I’m working on improving this now.
